### ISSUE TITLE
Explanation in Question 16 is not appropriate.

### ISSUE THREAD

**Issue by souvikpal2000** [SVCE-ACM/A-December-of-Algorithms-2022#37]
For Example if the Sample Input is 
1,1,1,1,1,1,1,6,7

According to your Explanation 6 & 7 are maximum heights.
So their is **1unit** gap between 6 & 7 and height will be **min(6,7)** which is **6units**. Resultant Area will be **6unit²**.

But if we take height at 0th Position which is **1** and height at 9th Position which is **7**, its resultant area will be **8unit²**.
**Calculation :** 
Their is **8units** gap between 1 & 7 and height will be **min(1,7)** which is **1unit**.

**Conslusion :** 
Area found with 2nd approach is greater than 1st approach.

**Comment by deepu2004** [comment]
The selected two heights need not necessarily be maximum.

Considering both the length and breadth to be maximum the area is found. So it is a combination of height and distance between the two heights.

So that the resultant area will be the maximum amount of water in the the given container.

**Comment by deepu2004** [comment]
heyy
The selected two heights need not necessarily be maximum

Considering both the length and breadth to be maximum the area is found. So it is a combination of height and distance between the two heights.

So that the resultant area will be the maximum amount of water in the the given container.

**Comment by deepu2004** [comment]
hey
The selected two heights need not necessarily be maximum but including the max distance between them at the same time.
considering both the length and breadth to be maximum the area is found. So it is a combination of height and distance between the two heights.
So that the resultant area will be the maximum amount of water in the the given container.
